# Generated by Django 2.2.12 on 2021-03-09 09:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('controldk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='exec_time',
        ),
        migrations.AddField(
            model_name='subsession',
            name='start_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='adapt',
            field=otree.db.models.PositiveIntegerField(choices=[[1, 'Ja'], [0, 'Nej']], null=True),
        ),
    ]
