# Generated by Django 2.2.12 on 2021-03-11 08:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('controldk', '0002_auto_20210309_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='subsession',
            name='exec_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
