# Generated by Django 2.2.12 on 2021-04-08 14:13

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models
import otreeutils.surveys


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey3rd_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey3rd_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session_name', otree.db.models.StringField(max_length=10000, null=True)),
                ('exec_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey3rd_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey3rd_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('s21_lookpainting', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s22_thingsinplace', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s23_remainunkind', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s24_nobodylikeme', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s25_afraidfeelingpain', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s26_hardtolie', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s27_sciboring', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s28_postponetask', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s29_criticism', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s210_gettouchstranger', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s211_worry', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s212_wondering', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s213_goodimg', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s214_precise', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s215_agreeothers', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s216_talkothers', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s217_overcome', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s218_famous', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s219_lovepeople', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s220_dothings', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s221_staycalm', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s222_wellmanner', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s223_tear', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('s224_soap', otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True)),
                ('email', otree.db.models.StringField(blank=True, default='', max_length=10000, null=True, verbose_name='E-mail:')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey3rd.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey3rd_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey3rd_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey3rd.Subsession')),
            ],
            options={
                'db_table': 'survey3rd_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin, otreeutils.surveys._SurveyModelMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey3rd.Subsession'),
        ),
    ]
