# Generated by Django 2.2.12 on 2021-04-08 15:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='s110_desc_climate_event',
            field=otree.db.models.StringField(blank=True, default='', max_length=10000, null=True, verbose_name='hvis ja, uddyb venligst:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s111_likelihood_climent_event',
            field=otree.db.models.StringField(choices=[['highly unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='Angiv, hvor sandsynligt du tror det ville være at blive udsat for ekstreme klimabegivenheder?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s112_degree_or_disagree',
            field=otree.db.models.StringField(choices=[['strongly agree', 'meget enig'], ['agree', 'enig'], ['neither agree nor disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongly disagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Vælg, hvor meget du er enig eller uenig i dette udsagn:\n Jeg har foretaget foranstaltninger for at mindske risikoen af at blive ramt af klimabegivenheder'),
        ),
        migrations.AddField(
            model_name='player',
            name='s11_gender',
            field=otree.db.models.StringField(choices=[['female', 'Kvinde'], ['male', 'Mand']], max_length=10000, null=True, verbose_name='Køn:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s12_age',
            field=otree.db.models.PositiveIntegerField(null=True, verbose_name='Alder:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s13_live_status',
            field=otree.db.models.StringField(choices=[['alone', 'Jeg bor alene'], ['with_partner', 'Je bor med min partner'], ['with_partner_and_children', 'Jeg bor med min partner og børn'], ['with_children', 'Jeg bor med mine børn']], max_length=10000, null=True, verbose_name='Hvordan bor du:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s14_monthly_income',
            field=otree.db.models.StringField(choices=[['above_40k', '40.000DKK eller over'], ['between', 'Mellem 25.000DKK and 40.000DKK'], ['less_25k', '25.000DKK eller under']], max_length=10000, null=True, verbose_name='Månedlig bruttoløn (før skat):'),
        ),
        migrations.AddField(
            model_name='player',
            name='s15_municipality',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Hvilken kommune er du bosat i:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s16_property_ownership',
            field=otree.db.models.StringField(choices=[['own', 'Ejerbolig'], ['rent', 'Leje'], ['others', 'Andet']], max_length=10000, null=True, verbose_name='Hvordan vil du beskrive din bolig ejerforhold?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s17_is_flood_risk_zone',
            field=otree.db.models.StringField(choices=[['no', 'Nej. Ingen risiko'], ['yes_medium', 'Ja. Mellem risiko'], ['yes_high', 'Ja. Høj risiko']], max_length=10000, null=True, verbose_name='Er din bolig i en oversvømmelsesrisikozone?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s18_house_type',
            field=otree.db.models.StringField(choices=[['duplex', 'Etagebolig'], ['detached_house', 'Parcelhus'], ['terraced_house', 'Rækkehus'], ['others', 'Andet']], max_length=10000, null=True, verbose_name='Hvordan vil du beskrive din boligtype?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s19_is_exposed_climate_event',
            field=otree.db.models.StringField(choices=[['yes', 'Ja'], ['no', 'Nej']], max_length=10000, null=True, verbose_name='Har du, et familiemedlem eller ven været udsat for klimarelateret begivenheder (f.eks. oversvømmelse)?'),
        ),
    ]
