# Generated by Django 2.2.12 on 2021-04-08 15:15

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0002_auto_20210408_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s112_degree_or_disagree',
            field=otree.db.models.StringField(choices=[['strongly agree', 'meget enig'], ['agree', 'enig'], ['neither agree nor disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongly disagree', 'meget uenig']], max_length=10000, null=True),
        ),
    ]
