# Generated by Django 2.2.12 on 2021-04-08 15:15

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0003_auto_20210408_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s111_likelihood_climent_event',
            field=otree.db.models.StringField(choices=[['highly unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly likely', 'højst sandsynligt']], max_length=10000, null=True),
        ),
    ]
