# Generated by Django 2.2.12 on 2021-04-08 15:15

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0004_auto_20210408_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s110_desc_climate_event',
            field=otree.db.models.StringField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
