# Generated by Django 2.2.12 on 2021-04-08 15:15

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0006_auto_20210408_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s18_house_type',
            field=otree.db.models.StringField(choices=[['duplex', 'Etagebolig'], ['detached_house', 'Parcelhus'], ['terraced_house', 'Rækkehus'], ['others', 'Andet']], max_length=10000, null=True),
        ),
    ]
