# Generated by Django 2.2.12 on 2021-04-08 15:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0007_auto_20210408_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s17_is_flood_risk_zone',
            field=otree.db.models.StringField(choices=[['no', 'Nej. Ingen risiko'], ['yes_medium', 'Ja. Mellem risiko'], ['yes_high', 'Ja. Høj risiko']], max_length=10000, null=True),
        ),
    ]
