# Generated by Django 2.2.12 on 2021-04-08 15:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0008_auto_20210408_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s16_property_ownership',
            field=otree.db.models.StringField(choices=[['own', 'Ejerbolig'], ['rent', 'Leje'], ['others', 'Andet']], max_length=10000, null=True),
        ),
    ]
