# Generated by Django 2.2.12 on 2021-04-08 15:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0009_auto_20210408_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s15_municipality',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
