# Generated by Django 2.2.12 on 2021-04-08 15:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0010_auto_20210408_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s14_monthly_income',
            field=otree.db.models.StringField(choices=[['above_40k', '40.000DKK eller over'], ['between', 'Mellem 25.000DKK and 40.000DKK'], ['less_25k', '25.000DKK eller under']], max_length=10000, null=True),
        ),
    ]
