# Generated by Django 2.2.12 on 2021-04-08 15:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0011_auto_20210408_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s13_live_status',
            field=otree.db.models.StringField(choices=[['alone', 'Jeg bor alene'], ['with_partner', 'Je bor med min partner'], ['with_partner_and_children', 'Jeg bor med min partner og børn'], ['with_children', 'Jeg bor med mine børn']], max_length=10000, null=True),
        ),
    ]
