# Generated by Django 2.2.12 on 2021-04-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0014_auto_20210408_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='s11_gender',
        ),
    ]
