# Generated by Django 2.2.12 on 2021-04-08 15:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0015_remove_player_s11_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='s11_gender',
            field=otree.db.models.StringField(choices=[('female', 'Kvinde'), ('male', 'Mand')], max_length=10000, null=True),
        ),
    ]
