# Generated by Django 2.2.12 on 2021-04-09 07:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0017_auto_20210408_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='s310_takecredit',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s311_rundownski',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s312_invest5perincome',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s313_whitewaterrafting',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s314_wageonmatch',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s315_unsupportedsex',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s316_revealsecret',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s317_drivecarnobelt',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s318_investstartup',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s319_learnparachute',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s31_diff_taste',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s320_ridemoto',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s321_choosecareer',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s322_sayunpopularcase',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s323_sunbathe',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s324_jumpbungee',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s325_takesmallplane',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s326_gohomealone',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s327_movetofarawaycity',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s328_startnewcareer',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s329_leavekidathome',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s32_camping',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s330_keeppurse',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s331_movehouse',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s332_sendkidtoschool',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s333_drivefloodedroad',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s334_parkcar',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s335_hiking',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s33_beghorseracing',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s34_investfund',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s35_drinking',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s36_taxdeduction',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s37_disagreeauth',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s38_stakepokergame',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s39_affair',
            field=otree.db.models.IntegerField(choices=[(1, 'højst usandsynligt'), (2, 'usandsynligt'), (3, 'ikke sikkert'), (4, 'sandsynligt'), (5, 'højst sandsynligt')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s410_takecredit',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s411_rundownski',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s412_invest5perincome',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s413_whitewaterrafting',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s414_wageonmatch',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s415_unsupportedsex',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s416_revealsecret',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s417_drivecarnobelt',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s418_investstartup',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s419_learnparachute',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s41_diff_taste',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s420_ridemoto',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s421_choosecareer',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s422_sayunpopularcase',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s423_sunbathe',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s424_jumpbungee',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s425_takesmallplane',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s426_gohomealone',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s427_movetofarawaycity',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s428_startnewcareer',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s429_leavekidathome',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s42_camping',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s430_keeppurse',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s431_movehouse',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s432_sendkidtoschool',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s433_drivefloodedroad',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s434_parkcar',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s435_hiking',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s43_beghorseracing',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s44_investfund',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s45_drinking',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s46_taxdeduction',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s47_disagreeauth',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s48_stakepokergame',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s49_affair',
            field=otree.db.models.IntegerField(choices=[(1, 'Slet ikke risikofyldt'), (2, 'Meget lidt risiko'), (3, 'Nogen risiko'), (4, 'Høj risiko'), (5, 'Allerhøjest risiko')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s112_degree_or_disagree',
            field=otree.db.models.StringField(choices=[['strongly agree', 'meget enig'], ['agree', 'enig'], ['neutral', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongly disagree', 'meget uenig']], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s14_monthly_income',
            field=otree.db.models.StringField(choices=[['above 40k', '40.000DKK eller over'], ['between', 'Mellem 25.000DKK and 40.000DKK'], ['less 25k', '25.000DKK eller under']], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s17_is_flood_risk_zone',
            field=otree.db.models.StringField(choices=[['no', 'Nej. Ingen risiko'], ['medium', 'Ja. Mellem risiko'], ['high', 'Ja. Høj risiko']], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s18_house_type',
            field=otree.db.models.StringField(choices=[['duplex', 'Etagebolig'], ['detached house', 'Parcelhus'], ['terraced house', 'Rækkehus'], ['others', 'Andet']], max_length=10000, null=True),
        ),
    ]
