# Generated by Django 2.2.12 on 2021-04-09 07:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0019_auto_20210409_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='s61_findsolution',
            field=otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s62_findvalue',
            field=otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s63_understand_issue',
            field=otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True),
        ),
    ]
