# Generated by Django 2.2.12 on 2021-04-09 07:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0020_auto_20210409_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='s71_adversity',
            field=otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s72_staycalm',
            field=otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='s73_meaning_exp',
            field=otree.db.models.IntegerField(choices=[(1, 'meget enig'), (2, 'enig'), (3, 'hverken enig eller uenig'), (4, 'uenig'), (5, 'meget uenig')], null=True),
        ),
    ]
