# Generated by Django 2.2.12 on 2021-04-09 12:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey3rd', '0032_auto_20210409_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s310_takecredit',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s311_rundownski',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s312_invest5perincome',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s313_whitewaterrafting',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s314_wageonmatch',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s315_unsupportedsex',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s316_revealsecret',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s317_drivecarnobelt',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s318_investstartup',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s319_learnparachute',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s31_diff_taste',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s320_ridemoto',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s321_choosecareer',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s322_sayunpopularcase',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s323_sunbathe',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s324_jumpbungee',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s325_takesmallplane',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s326_gohomealone',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s327_movetofarawaycity',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s328_startnewcareer',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s329_leavekidathome',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s32_camping',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s330_keeppurse',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s331_movehouse',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s332_sendkidtoschool',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s333_drivefloodedroad',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s334_parkcar',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s335_hiking',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s33_beghorseracing',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s34_investfund',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s35_drinking',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s36_taxdeduction',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s37_disagreeauth',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s38_stakepokergame',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='s39_affair',
            field=otree.db.models.IntegerField(choices=[(1, 'Højst usandsynligt'), (2, 'Usandsynligt'), (3, 'Ikke sikkert'), (4, 'Sandsynligt'), (5, 'Højst sandsynligt')], null=True),
        ),
    ]
