# Generated by Django 2.2.12 on 2021-03-09 09:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey2nd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s61_movehouse',
            field=otree.db.models.StringField(choices=[['Not risky at all', 'Slet ikke risikofyldt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='…flytte til et hus beliggende langs bredden af en flod'),
        ),
    ]
