# Generated by Django 2.2.12 on 2021-03-09 09:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey2nd', '0005_auto_20210309_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='s61_movehouse',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='…flytte til et hus beliggende langs bredden af en flod'),
        ),
        migrations.AlterField(
            model_name='player',
            name='s62_sendkidtoschool',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='…sende børn i skolen, imens DMI varsler om farligt vejr i dit område'),
        ),
        migrations.AlterField(
            model_name='player',
            name='s63_drivefloodedroad',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='…køre på en oversvømmet vej.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='s64_parkcar',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='…parkere din bil i et udsat område, imens DMI varsler om farligt vejr i regionen.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='s65_hiking',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='…gå på vandreture, imens DMI varsler om farligt vejr i området.'),
        ),
    ]
