# Generated by Django 2.2.12 on 2021-04-12 12:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey2nd', '0014_auto_20210402_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='s21_prefered_option',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s22_program_ab',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s23_program_cd',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s31_findsolution',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s32_findvalue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s33_understand_issue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s41_adversity',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s42_staycalm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s43_meaning_exp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s510_takecredit',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s511_rundownski',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s512_invest5perincome',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s513_whitewaterrafting',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s514_wageonmatch',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s515_unsupportedsex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s516_revealsecret',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s517_drivecarnobelt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s518_investstartup',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s519_learnparachute',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s51_diff_taste',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s520_ridemoto',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s521_choosecareer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s522_sayunpopularcase',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s523_sunbathe',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s524_jumpbungee',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s525_takesmallplane',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s526_gohomealone',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s527_movetofarawaycity',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s528_startnewcareer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s529_leavekidathome',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s52_camping',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s530_keeppurse',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s531_movehouse',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s532_sendkidtoschool',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s533_drivefloodedroad',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s534_parkcar',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s535_hiking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s53_beghorseracing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s54_investfund',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s55_drinking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s56_taxdeduction',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s57_disagreeauth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s58_stakepokergame',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s59_affair',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s610_takecredit',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s611_rundownski',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s612_invest5perincome',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s613_whitewaterrafting',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s614_wageonmatch',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s615_unsupportedsex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s616_revealsecret',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s617_drivecarnobelt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s618_investstartup',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s619_learnparachute',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s61_diff_taste',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s620_ridemoto',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s621_choosecareer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s622_sayunpopularcase',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s623_sunbathe',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s624_jumpbungee',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s625_takesmallplane',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s626_gohomealone',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s627_movetofarawaycity',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s628_startnewcareer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s629_leavekidathome',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s62_camping',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s630_keeppurse',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s631_movehouse',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s632_sendkidtoschool',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s633_drivefloodedroad',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s634_parkcar',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s635_hiking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s63_beghorseracing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s64_investfund',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s65_drinking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s66_taxdeduction',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s67_disagreeauth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s68_stakepokergame',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s69_affair',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s710_gettouchstranger',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s711_worry',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s712_wondering',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s713_goodimg',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s714_precise',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s715_agreeothers',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s716_talkothers',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s717_overcome',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s718_famous',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s719_lovepeople',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s71_lookpainting',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s720_dothings',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s721_staycalm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s722_wellmanner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s723_tear',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s724_soap',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s72_thingsinplace',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s73_remainunkind',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s74_nobodylikeme',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s75_afraidfeelingpain',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s76_hardtolie',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s77_sciboring',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s78_postponetask',
        ),
        migrations.RemoveField(
            model_name='player',
            name='s79_criticism',
        ),
        migrations.AddField(
            model_name='player',
            name='s210_gettouchstranger',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg har let ved at tage kontakt til fremmede.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s211_worry',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg bekymrer mig mindre end andre.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s212_wondering',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg gad godt vide, hvordan man på uærlig vis kan tjene en masse penge.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s213_goodimg',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg har en god fantasi.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s214_precise',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg arbejder meget præcist.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s215_agreeothers',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg enes hurtigt med andre.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s216_talkothers',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg kan lide at snakke med andre.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s217_overcome',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg overvinder let problemer på egen hånd.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s218_famous',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg vil gerne være berømt.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s219_lovepeople',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg elsker mennesker med mærkelige idéer.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s21_lookpainting',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg kan se på et maleri i lang tid.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s220_dothings',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg gør ofte ting uden rigtigt at tænke.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s221_staycalm',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Selv når jeg bliver behandlet dårligt, forbliver jeg rolig.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s222_wellmanner',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg  er sjældent veloplagt.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s223_tear',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg fælder en tåre, når jeg ser sørgelige eller romantiske film.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s224_soap',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg har krav på særbehandling.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s22_thingsinplace',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg sørger for, at mine ting altid er på deres plads.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s23_remainunkind',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg forbliver uvenlig overfor nogen, som har været ondsindet overfor mod mig.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s24_nobodylikeme',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Ingen kan lide at tale  med mig.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s25_afraidfeelingpain',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg er bange for at føle smerte.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s26_hardtolie',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg har svært ved at lyve.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s27_sciboring',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg synes, at videnskab er kedeligt.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s28_postponetask',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg udskyder indviklede opgaver så længe som muligt'),
        ),
        migrations.AddField(
            model_name='player',
            name='s29_criticism',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg giver ofte kritik.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s310_takecredit',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… tage æren for en anden persons arbejde?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s311_rundownski',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… køre ned ad en skiløjpe, der er vanskeligere end dine evner rækker til?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s312_invest5perincome',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… investere 5% af din årsindtægt i en stærkt spekulativ aktie?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s313_whitewaterrafting',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… tage på white water rafting om foråret når strømmen er stærkest?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s314_wageonmatch',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… satse en dagløn på en sportskamp (f.eks. fodbold, boksning eller håndbold)?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s315_unsupportedsex',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… dyrke ubeskyttet sex?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s316_revealsecret',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… røbe en vens hemmelighed til en anden person?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s317_drivecarnobelt',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… køre i bil uden sele?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s318_investstartup',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… investere 10% af din årsindtægt i en nystartet virksomhed?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s319_learnparachute',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… lære at springe i faldskærm?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s31_diff_taste',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… indrømme, at du har en anderledes smag end dine venner?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s320_ridemoto',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… køre på motorcykel uden hjelm?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s321_choosecareer',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… vælge en karriere du virkelig føler for, i stedet for en mere sikker karriere?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s322_sayunpopularcase',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… sige hvad du mener om en upopulær sag til et møde på arbejdet?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s323_sunbathe',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… tage solbad uden solcreme?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s324_jumpbungee',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… springe bungy-jump fra en høj bro?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s325_takesmallplane',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… flyve en lille flyvemaskine?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s326_gohomealone',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… gå alene hjem om natten gennem et af byens farlige kvarterer?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s327_movetofarawaycity',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… flytte til en by langt væk fra din familie?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s328_startnewcareer',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name="… påbegynde en ny karriere midt i 30'erne?"),
        ),
        migrations.AddField(
            model_name='player',
            name='s329_leavekidathome',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… efterlade dine små børn alene hjemme, imens du løber et ærinde?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s32_camping',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… campere ude i vildmarken?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s330_keeppurse',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… beholde en pung du har fundet, som indeholder 1.000 kroner?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s331_movehouse',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… flytte til et hus, som ligger langs bredden af en flod:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s332_sendkidtoschool',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… sende børn i skolen, imens DMI varsler om farligt vejr i dit område:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s333_drivefloodedroad',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… køre på en oversvømmet vej.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s334_parkcar',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… parkere din bil i et udsat område, imens DMI varsler om farligt vejr i regionen.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s335_hiking',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… tage på vandreture, imens DMI varsler om farligt vejr i området.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s33_beghorseracing',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… satse en dagløn på hestevæddeløb?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s34_investfund',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… investere 10% af din årsløn i en pensionsfond?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s35_drinking',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… drikke store mængder alkohol ved et socialt arrangement?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s36_taxdeduction',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… angive et lidt for højt fradrag til SKAT?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s37_disagreeauth',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… erklære dig uenig med en autoritet, hvad angår et vigtigt emne?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s38_stakepokergame',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… satse en dagløn på et pokerspil med høje indsatser?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s39_affair',
            field=otree.db.models.StringField(choices=[['highly_unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not_certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly_likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='… have en affære med en gift person?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s410_takecredit',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… tage æren for en anden persons arbejde?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s411_rundownski',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… køre ned ad en skiløjpe, der er vanskeligere end dine evner rækker til?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s412_invest5perincome',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… investere 5% af din årsindtægt i en stærkt spekulativ aktie?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s413_whitewaterrafting',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… tage på white water rafting om foråret når strømmen er stærkest?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s414_wageonmatch',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… satse en dagløn på en sportskamp (f.eks. fodbold, boksning eller håndbold)??'),
        ),
        migrations.AddField(
            model_name='player',
            name='s415_unsupportedsex',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… dyrke ubeskyttet sex?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s416_revealsecret',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… røbe en vens hemmelighed til en anden person?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s417_drivecarnobelt',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… køre i bil uden sele?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s418_investstartup',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… investere 10% af din årsindtægt i en nystartet virksomhed?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s419_learnparachute',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… lære at springe i faldskærm?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s41_diff_taste',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… indrømme, at du har en anderledes smag end dine venner?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s420_ridemoto',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… køre på motorcykel uden hjelm?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s421_choosecareer',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… vælge en karriere du virkelig føler for, i stedet for en mere sikker karriere?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s422_sayunpopularcase',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… sige hvad du mener om en upopulær sag til et møde på arbejdet?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s423_sunbathe',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… tage solbad uden solcreme?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s424_jumpbungee',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… springe bungy-jump fra en høj bro?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s425_takesmallplane',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… flyve en lille flyvemaskine?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s426_gohomealone',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… gå alene hjem om natten gennem et af byens farlige kvarterer?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s427_movetofarawaycity',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… flytte til en by langt væk fra din familie?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s428_startnewcareer',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name="… påbegynde en ny karriere midt i 30'erne?"),
        ),
        migrations.AddField(
            model_name='player',
            name='s429_leavekidathome',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… efterlade dine små børn alene hjemme, imens du løber et ærinde?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s42_camping',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… campere ude i vildmarken?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s430_keeppurse',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… beholde en pung du har fundet, som indeholder 1.000 kroner?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s431_movehouse',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… flytte til et hus beliggende langs bredden af en flod:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s432_sendkidtoschool',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… sende børn i skolen, imens DMI varsler om farligt vejr i dit område:'),
        ),
        migrations.AddField(
            model_name='player',
            name='s433_drivefloodedroad',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… køre på en oversvømmet vej.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s434_parkcar',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… parkere din bil i et udsat område, imens DMI varsler om farligt vejr i regionen.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s435_hiking',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… tage på vandreture, imens DMI varsler om farligt vejr i området.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s43_beghorseracing',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… satse en dagløn på hestevæddeløb?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s44_investfund',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… investere 10% af din årsløn i en pensionsfond?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s45_drinking',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… drikke store mængder alkohol ved et socialt arrangement?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s46_taxdeduction',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… angive et lidt for højt fradrag til SKAT?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s47_disagreeauth',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… erklære dig uenig med en autoritet hvad angår et vigtigt emne?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s48_stakepokergame',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… satse en dagløn på et pokerspil med høje indsatser?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s49_affair',
            field=otree.db.models.StringField(choices=[['Not_risky_at_all', 'Slet ikke risikofyldt'], ['Very_little_risk', 'Meget lidt risiko'], ['No_risk', 'Nogen risiko'], ['High_risk', 'Høj risiko'], ['Very_high_risk', 'Allerhøjest risiko']], max_length=10000, null=True, verbose_name='… have en affære med en gift person?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s51_prefered_option',
            field=otree.db.models.StringField(choices=[['flatorcrown', 'Slå plat eller krone og vind 10.000 DKK med 50 procents sandsynlighed og 50 procents sandsynlighed for ingenting '], ['win5kddk', 'Vind 5.000 DKK med sikkerhed'], ['nomatter', 'Ligegyldigt, jeg synes begge muligheder er lige gode']], max_length=10000, null=True, verbose_name='Hvilken mulighed ville du foretrække?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s52_program_ab',
            field=otree.db.models.StringField(choices=[['progA', 'Scenarie A: 200 mennesker bliver reddet med sikkerhed, de resterende 400 er for usikkert til at kunne komme med et estimat.'], ['progB', 'Scenarie B: Der er en tredjedel (33,3%) sandsynlighed for, at 600 mennesker bliver reddet, og to tredjedels (66,6%) sandsynlighed for, at ingen mennesker bliver reddet.']], max_length=10000, null=True, verbose_name='Hvilke af de to forslag vil du foretrække?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s53_program_cd',
            field=otree.db.models.StringField(choices=[['progC', 'Scenarie C: 400 mennesker vil omkomme med sikkerhed, de resterende 200 er for usikkert til at kunne komme med et estimat.'], ['progD', 'Scenarie D: Der er en tredjedel (33,3%) sandsynlighed for, at ingen mennesker vil omkomme og to tredjedele (66,6%) sandsynlighed for, at 600 mennesker vil omkomme.']], max_length=10000, null=True, verbose_name='Regeringen fremsætter to yderligere scenarier, hvilket vil du foretrække?'),
        ),
        migrations.AddField(
            model_name='player',
            name='s61_findsolution',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg er god til at finde løsninger på forskellige udfordringer og problemer, som opstår i min hverdag.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s62_findvalue',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg oplever, at udfordringer og problemhåndtering skaber værdi for mit liv.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s63_understand_issue',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Jeg er god til at forudse forskellige udfordringer og problemer i mit liv, og forstå deres betydning for mit liv.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s71_adversity',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='De vil med stor sandsynlighed overvinde mange af de udfordringer, der opstår i kølvandet på oversvømmelsen.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s72_staycalm',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='De vil stille og roligt vurdere, hvad de skal gøre.'),
        ),
        migrations.AddField(
            model_name='player',
            name='s73_meaning_exp',
            field=otree.db.models.StringField(choices=[['strongly_agree', 'meget enig'], ['agree', 'enig'], ['n_agree_disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongdisagree', 'meget uenig']], max_length=10000, null=True, verbose_name='De vil finde en mening med denne oplevelse.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='s17_is_flood_risk_zone',
            field=otree.db.models.StringField(choices=[['no', 'Nej. Ingen risiko'], ['yes_medium', 'Ja. Mellem risiko'], ['yes_high', 'Ja. Høj risiko']], max_length=10000, null=True, verbose_name='Er din bolig i en oversvømmelsesrisikozone?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='s18_house_type',
            field=otree.db.models.StringField(choices=[['duplex', 'Etagebolig'], ['detached_house', 'Parcelhus'], ['terraced_house', 'Rækkehus'], ['others', 'Andet']], max_length=10000, null=True, verbose_name='Hvordan vil du beskrive din boligtype?'),
        ),
    ]
