# Generated by Django 2.2.12 on 2021-04-12 12:50

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey2nd1_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey2nd1_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session_name', otree.db.models.StringField(max_length=10000, null=True)),
                ('exec_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey2nd1_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey2nd1_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('s11_gender', otree.db.models.StringField(choices=[['female', 'Kvinde'], ['male', 'Mand']], max_length=10000, null=True, verbose_name='Køn:')),
                ('s12_age', otree.db.models.PositiveIntegerField(null=True, verbose_name='Alder:')),
                ('s13_live_status', otree.db.models.StringField(choices=[['alone', 'Jeg bor alene'], ['with_partner', 'Je bor med min partner'], ['with_partner_and_children', 'Jeg bor med min partner og børn'], ['with_children', 'Jeg bor med mine børn']], max_length=10000, null=True, verbose_name='Hvordan bor du:')),
                ('s14_monthly_income', otree.db.models.StringField(choices=[['above_40k', '40.000DKK eller over'], ['between', 'Mellem 25.000DKK and 40.000DKK'], ['less_25k', '25.000DKK eller under']], max_length=10000, null=True, verbose_name='Månedlig bruttoløn (før skat):')),
                ('s15_municipality', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Hvilken kommune er du bosat i:')),
                ('s16_property_ownership', otree.db.models.StringField(choices=[['own', 'Ejerbolig'], ['rent', 'Leje'], ['others', 'Andet']], max_length=10000, null=True, verbose_name='Hvordan vil du beskrive din bolig ejerforhold?')),
                ('s17_is_flood_risk_zone', otree.db.models.StringField(choices=[['no', 'Nej. Ingen risiko'], ['yes_medium', 'Ja. Mellem risiko'], ['yes_high', 'Ja. Høj risiko']], max_length=10000, null=True, verbose_name='Er din bolig i en oversvømmelsesrisikozone?')),
                ('s18_house_type', otree.db.models.StringField(choices=[['duplex', 'Etagebolig'], ['detached_house', 'Parcelhus'], ['terraced_house', 'Rækkehus'], ['others', 'Andet']], max_length=10000, null=True, verbose_name='Hvordan vil du beskrive din boligtype?')),
                ('s19_is_exposed_climate_event', otree.db.models.StringField(choices=[['yes', 'Ja'], ['no', 'Nej']], max_length=10000, null=True, verbose_name='Har du, et familiemedlem eller ven været udsat for klimarelateret begivenheder (f.eks. oversvømmelse)?')),
                ('s110_desc_climate_event', otree.db.models.StringField(blank=True, default='', max_length=10000, null=True, verbose_name='hvis ja, uddyb venligst:')),
                ('s111_likelihood_climent_event', otree.db.models.StringField(choices=[['highly unlikely', 'højst usandsynligt'], ['unlikely', 'usandsynligt'], ['not certain', 'ikke sikkert'], ['likely', 'sandsynligt'], ['highly likely', 'højst sandsynligt']], max_length=10000, null=True, verbose_name='Angiv, hvor sandsynligt du tror det ville være at blive udsat for ekstreme klimabegivenheder?')),
                ('s112_degree_or_disagree', otree.db.models.StringField(choices=[['strongly agree', 'meget enig'], ['agree', 'enig'], ['neither agree nor disagree', 'hverken enig eller uenig'], ['disagree', 'uenig'], ['strongly disagree', 'meget uenig']], max_length=10000, null=True, verbose_name='Vælg, hvor meget du er enig eller uenig i dette udsagn:\n Jeg har foretaget foranstaltninger for at mindske risikoen af at blive ramt af klimabegivenheder')),
                ('s21_prefered_option', otree.db.models.StringField(choices=[['flatorcrown', 'Slå plat eller krone og vind 10.000 DKK med 50 procents sandsynlighed og 50 procents sandsynlighed for ingenting '], ['win5kddk', 'Vind 5.000 DKK med sikkerhed'], ['nomatter', 'Ligegyldigt, jeg synes begge muligheder er lige gode']], max_length=10000, null=True, verbose_name='Hvilken mulighed ville du foretrække?')),
                ('s22_program_ab', otree.db.models.StringField(choices=[['progA', 'Scenarie A: 200 mennesker bliver reddet med sikkerhed, de resterende 400 er for usikkert til at kunne komme med et estimat.'], ['progB', 'Scenarie B: Der er en tredjedel (33,3%) sandsynlighed for, at 600 mennesker bliver reddet, og to tredjedels (66,6%) sandsynlighed for, at ingen mennesker bliver reddet.']], max_length=10000, null=True, verbose_name='Hvilke af de to forslag vil du foretrække?')),
                ('s23_program_cd', otree.db.models.StringField(choices=[['progC', 'Scenarie C: 400 mennesker vil omkomme med sikkerhed, de resterende 200 er for usikkert til at kunne komme med et estimat.'], ['progD', 'Scenarie D: Der er en tredjedel (33,3%) sandsynlighed for, at ingen mennesker vil omkomme og to tredjedele (66,6%) sandsynlighed for, at 600 mennesker vil omkomme.']], max_length=10000, null=True, verbose_name='Regeringen fremsætter to yderligere scenarier, hvilket vil du foretrække?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey2nd1.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey2nd1_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey2nd1_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey2nd1.Subsession')),
            ],
            options={
                'db_table': 'survey2nd1_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey2nd1.Subsession'),
        ),
    ]
