# Generated by Django 2.2.12 on 2021-03-09 22:17

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveydospert_group', to='otree.Session')),
            ],
            options={
                'db_table': 'surveydospert_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session_name', otree.db.models.StringField(max_length=10000, null=True)),
                ('exec_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveydospert_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'surveydospert_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('q1', otree.db.models.StringField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], max_length=10000, null=True)),
                ('q2', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q3', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q4', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q5', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q6', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q7', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q8', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q9', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q10', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q11', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q12', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q13', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q14', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q15', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q16', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q17', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q18', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q19', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q20', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q21', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q22', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q23', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q24', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q25', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q26', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q27', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q28', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q29', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q30', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q31', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q32', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q33', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q34', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('q35', otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveydospert.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveydospert_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveydospert_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveydospert.Subsession')),
            ],
            options={
                'db_table': 'surveydospert_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveydospert.Subsession'),
        ),
    ]
