# Generated by Django 2.2.12 on 2021-03-09 22:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveydospert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='q1',
            field=otree.db.models.PositiveIntegerField(choices=[[1, '1 = slet ikke risikofyldt'], [2, '2 = meget lidt risiko'], [3, '3 = nogen risiko'], [4, '4 = høj risiko'], [5, '5 = allerhøjest risiko']], null=True),
        ),
    ]
